apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
spec:
  selector:
    matchLabels:
      app: openwebui
  replicas: 1
  template:
    metadata:
      labels:
        app: openwebui
    spec:
      containers:
      - name: openwebui
        image: ghcr.io/open-webui/open-webui
        ports:
        - containerPort: 11434
