grafana:
  service:
    type: NodePort

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'ollama-blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
              - ollama.ollama.svc.cluster.local:11434/api/tags
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-prometheus-blackbox-exporter.default.svc.cluster.local:9115
