apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ollama-exporter
  namespace: ollama
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: ollama
  namespaceSelector:
    matchNames:
      - ollama
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
