apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
spec:
  selector:
    matchLabels:
      app: ollama
  replicas: 1
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: alpine/ollama
        ports:
        - containerPort: 11434
      - name: ollama-exporter
        image: karshkoff/ollama-prom-exporter
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-svc
  namespace: ollama
spec:
  type: NodePort
  selector:
    app: ollama
  ports:
  - name: ollama
    port: 11434
    targetPort: 11434
  - name: ollama-exporter
    port: 8088
    targetPort: 8088
