name: Build and Deploy to Kubernetes
run-name: "Run_id: ${{ github.run_id }}"

env:
  AWS_REGION: "us-east-1"

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: 'Buid and Push Docker Image'
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ollama-prom-exporter:latest

  deploy:
    name: 'Deploy to EKS'
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Configure kubectl
      uses: aws-actions/configure-eks@v2
      with:
        cluster-name: j-llm-dev
        region: ${{ env.AWS_REGION }}

    - name: Deploy to EKS
      run: |
        kubectl apply -k k8s/app/
